/*
 * ISO8583 API
 *
 * Package github.com/moov-io/iso8583 implements a file reader and writer written in Go decorated with a HTTP API for creating, parsing, and validating financial transaction card originated interchange messaging. User can seed iso8583's specification file as json file, iso8583 message with several formsts (mesage binary, json, xml)  | Input      | Output     |  |------------|------------|  | JSON       | JSON       |  | XML        | XML        |  | MESSAGE    | MESSAGE    |
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Element struct for Element
type Element struct {
	Type           string   `json:"type,omitempty"`
	Length         int32    `json:"length,omitempty"`
	Format         string   `json:"format,omitempty"`
	Encoding       string   `json:"encoding,omitempty"`
	Fixed          bool     `json:"fixed,omitempty"`
	LengthEncoding string   `json:"length_encoding,omitempty"`
	DataLength     int32    `json:"data_length,omitempty"`
	Value          []string `json:"value,omitempty"`
}
