/*
 * ISO8583 API
 *
 * Package github.com/moov-io/iso8583 implements a file reader and writer written in Go decorated with a HTTP API for creating, parsing, and validating financial transaction card originated interchange messaging. User can seed iso8583's specification file as json file, iso8583 message with several formsts (mesage binary, json, xml)  | Input      | Output     |  |------------|------------|  | JSON       | JSON       |  | XML        | XML        |  | MESSAGE    | MESSAGE    |
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Encoding struct for Encoding
type Encoding struct {
	MtiEnc string `json:"mti_enc,omitempty"`
	BmpEnc string `json:"bmp_enc,omitempty"`
	LenEnc string `json:"len_enc,omitempty"`
	NumEnc string `json:"num_enc,omitempty"`
	ChrEnc string `json:"chr_enc,omitempty"`
	BinEnc string `json:"bin_enc,omitempty"`
	TrkEnc string `json:"trk_enc,omitempty"`
}
